name: Git-hooks Pipeline

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Prepare Scripts
          - chmod +x scripts/*
      - name: Lint
        run: |
          scripts/lint.sh
      - name: Test
        run: |
          pytest --doctest-modules --cov=src/main/
      - name: Package
        run: |
          pyinstaller --onefile src/main/commit_msg_hook.py --name commit_msg.exe
